Setup env

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
!cp /content/drive/MyDrive/LicheeRV_Nano_Resources/tpu-mlir_v1.9.beta.0-110-gfdb73ce31-20240719.tar.gz tpu-mlir.tar.gz
!mkdir tpu_mlir
!tar -xzf tpu-mlir.tar.gz -C tpu_mlir --strip-components=1
!mv ./tpu_mlir/$(ls ./tpu_mlir) ./tpu_mlir/source
!wget https://github.com/sophgo/tpu-mlir/releases/download/v1.14/tpu_mlir-1.14-py3-none-any.whl
!sudo add-apt-repository ppa:deadsnakes/ppa -y
!sudo apt update
!sudo apt install python3.10
!wget https://bootstrap.pypa.io/get-pip.py
!python3.10 get-pip.py
!python3.10 -m pip install tpu_mlir-1.14-py3-none-any.whl
!python3.10 -m pip install flatbuffers
!python3.10 -m pip install ultralytics
!python3.10 -m pip install onnxsim
!mkdir work
%cd work

--2025-03-18 20:48:58--  https://github.com/sophgo/tpu-mlir/releases/download/v1.14/tpu_mlir-1.14-py3-none-any.whl
Resolving github.com (github.com)... 140.82.114.4
Connecting to github.com (github.com)|140.82.114.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://objects.githubusercontent.com/github-production-release-asset-2e65be/499493110/000ec863-8eaa-4594-9701-217373bc698b?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20250318%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20250318T204858Z&X-Amz-Expires=300&X-Amz-Signature=325ae4d2c25f7df1340ad5c12a78a5a28aed2f25663cbbe51822d5f27f246adf&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%3Dtpu_mlir-1.14-py3-none-any.whl&response-content-type=application%2Foctet-stream [following]
--2025-03-18 20:48:58--  https://objects.githubusercontent.com/github-production-release-asset-2e65be/499493110/000ec863-8eaa-4594-9701-217373bc698b?X-Amz-Algorithm=

In [4]:
# %cd work

In [11]:
!python3.10 -m pip install onnxscript onnxruntime
!python3 -m pip install onnxscript onnxruntime


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.0/16.0 MB 104.1 MB/s eta 0:00:00
  Using cached coloredlogs-15.0.1-py2.py3-none-any.whl.metadata (12 kB)
  Using cached humanfriendly-10.0-py2.py3-none-any.whl.metadata (9.2 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.0/16.0 MB 82.6 MB/s eta 0:00:00
Using cached coloredlogs-15.0.1-py2.py3-none-any.whl (46 kB)
Using cached humanfriendly-10.0-py2.py3-none-any.whl (86 kB)


In [5]:
import torch
import torch.nn as nn
import torch.nn.functional as F


# DQN arch
class DQN(nn.Module):

    def __init__(self, n_observations, n_actions):
        super(DQN, self).__init__()
        self.layer1 = nn.Linear(n_observations, 128)
        self.layer2 = nn.Linear(128, 128)
        self.layer3 = nn.Linear(128, n_actions)

    def forward(self, x):
        x = F.relu(self.layer1(x))
        x = F.relu(self.layer2(x))
        return self.layer3(x)


In [40]:
policy_net = DQN(4, 2)
policy_net.load_state_dict(torch.load("/content/trained.pth", map_location=torch.device('cpu')))
policy_net.eval()
print(policy_net(torch.tensor([-0.03209978, -0.0461358 , -0.01805152,  0.03391415]))) # Test
onnx_program = torch.onnx.dynamo_export(policy_net, torch.randn(1, 4))
onnx_program.save("/content/dqn.onnx")

tensor([96.1251, 95.9017], grad_fn=<ViewBackward0>)


/usr/local/lib/python3.11/dist-packages/torch/onnx/_internal/_exporter_legacy.py:101: UserWarning: torch.onnx.dynamo_export only implements opset version 18 for now. If you need to use a different opset version, please register them with register_custom_op.
  warnings.warn(


In [9]:
import os

os.environ['MODEL_NAME'] = "dqn"

In [36]:
inp = np.load("/content/calib_output.npz", allow_pickle=True)
print(inp["arr_0"])

{'0': array([[0]]), '1': array([[0]]), '2': array([[1]]), '3': array([[1]]), '4': array([[0]]), '5': array([[1]]), '6': array([[1]]), '7': array([[0]]), '8': array([[1]]), '9': array([[0]]), '10': array([[1]]), '11': array([[0]]), '12': array([[0]]), '13': array([[1]]), '14': array([[1]]), '15': array([[0]]), '16': array([[1]]), '17': array([[0]]), '18': array([[0]]), '19': array([[1]]), '20': array([[1]]), '21': array([[0]]), '22': array([[1]]), '23': array([[0]]), '24': array([[1]]), '25': array([[0]]), '26': array([[0]]), '27': array([[1]]), '28': array([[1]]), '29': array([[0]]), '30': array([[1]]), '31': array([[0]]), '32': array([[1]]), '33': array([[0]]), '34': array([[0]]), '35': array([[1]]), '36': array([[1]]), '37': array([[0]]), '38': array([[1]]), '39': array([[0]]), '40': array([[1]]), '41': array([[0]]), '42': array([[0]]), '43': array([[1]]), '44': array([[1]]), '45': array([[0]]), '46': array([[1]]), '47': array([[0]]), '48': array([[0]]), '49': array([[1]]), '50': arr

In [30]:
import numpy as np

# inp = np.load("/content/calib_input.npz", allow_pickle=True)
# print(inp["arr_0"])
with open("/content/test_input.npy", "wb") as fd:
  np.save(fd, np.array([[-0.03209978, -0.0461358 , -0.01805152,  0.03391415]], dtype=np.float64))

In [45]:
%cd /content
!rm -rf work
!mkdir work
%cd work

/content
/content/work


In [46]:
!export PYTHONPATH=/usr/bin/python3.10
!source ../tpu_mlir/source/envsetup.sh
!echo $MODEL_NAME
!model_transform.py --model_name $MODEL_NAME --model_def ../$MODEL_NAME.onnx --input_shapes "[[1, 4]]" --mean 0.0,0.0,0.0,0.0 --scale 1,1,1,1 --mlir $MODEL_NAME.mlir --test_input /content/test_input.npy --test_result /content/mlir_res.npz

dqn
2025/03/18 21:24:11 - INFO : TPU-MLIR v1.14-20241231
2025/03/18 21:24:11 - INFO : 
	 _____________________________________________________ 
	| preprocess:                                           |
	|   (x - mean) * scale                                  |
	'-------------------------------------------------------'
  config Preprocess args : 
	resize_dims           : same to net input dims
	keep_aspect_ratio     : False
	keep_ratio_mode       : letterbox
	pad_value             : 0
	pad_type              : center
	--------------------------
	mean                  : [0.0, 0.0, 0.0, 0.0]
	scale                 : [1.0, 1.0, 1.0, 1.0]
	--------------------------
	pixel_format          : bgr
	channel_format        : nchw

2025/03/18 21:24:11 - INFO : Input_shape assigned
2025/03/18 21:24:11 - INFO : ConstantFolding finished
2025/03/18 21:24:11 - INFO : skip_fuse_bn:False
2025/03/18 21:24:12 - INFO : Onnxsim opt finished
2025/03/18 21:24:12 - INFO : ConstantFolding finished
2025/03/18 21:

In [48]:
out = np.load("/content/mlir_res.npz", allow_pickle=True)
print(out["layer3_1_Gemm"])

[[96.12512 95.90169]]


In [54]:
# with open("/content/test_input.npy", "wb") as fd:
#   np.save(fd, np.array([[-0.03209978, -0.0461358 , -0.01805152,  0.03391415]], dtype=np.float64))

np.savez("/content/test_input.npz", **{"arr_2d": np.array([[-0.03209978, -0.0461358 , -0.01805152,  0.03391415]], dtype=np.float32)})

In [55]:
!export PYTHONPATH=/usr/bin/python3.10
!source ../tpu_mlir/source/envsetup.sh

!model_deploy \
--mlir $MODEL_NAME.mlir \
--quant_input \
--test_input /content/test_input.npz \
--quantize bf16 \
--processor cv181x \
--tolerance 0.99,0.99 \
--model dqn.cvimodel

2025/03/18 21:29:16 - INFO : TPU-MLIR v1.14-20241231
[CMD]: model_runner.py --input dqn_in_f32.npz --model dqn.mlir --output dqn_top_outputs.npz  
[                                                  ] 0%                                                  ] 0%#                         ] 50%#] 100%
[Running]: tpuc-opt dqn.mlir --processor-assign="chip=cv181x mode=BF16 num_device=1 num_core=1 addr_mode=auto" --processor-top-optimize --convert-top-to-tpu=" asymmetric=False doWinograd=False ignore_f16_overflow=False q_group_size=0 matmul_perchannel=False gelu_mode=normal" --canonicalize --weight-fold -o dqn_cv181x_bf16_tpu.mlir
[Success]: tpuc-opt dqn.mlir --processor-assign="chip=cv181x mode=BF16 num_device=1 num_core=1 addr_mode=auto" --processor-top-optimize --convert-top-to-tpu=" asymmetric=False doWinograd=False ignore_f16_overflow=False q_group_size=0 matmul_perchannel=False gelu_mode=normal" --ca

In [58]:
!model_runner.py --input /content/test_input.npz --model dqn.cvimodel --output dqn_cv181x_bf16_model_outputs.npz

setenv:cv181x
Start TPU Simulator for cv181x
device[0] opened, 4294967296
version: 1.4.0
dqn Build at 2025-03-18 21:29:17 For platform cv181x
Cmodel: bm_load_cmdbuf
Max SharedMem size:512
Cmodel: bm_run_cmdbuf
device[0] closed

Saving ...

Result saved to:dqn_cv181x_bf16_model_outputs.npz


In [60]:
np.load("dqn_cv181x_bf16_model_outputs.npz")["layer3_1_Gemm_f32"]

array([[[[96.]],

        [[96.]]]], dtype=float32)